// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "fSzrSy47jiHFxIKroQQHMIGfEO6DKQlVzCrNdpZpgZjs4Ww1WVrxGBsBTqYQyqXGxco4Y2";
}
}
}

